In [1]:
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import statsmodels.api as sm
from matplotlib.ticker import FuncFormatter, PercentFormatter

# import auri
plt.style.use("./auri.mplstyle")
pd.options.display.unicode.east_asian_width = True

np.random.seed(1106)

In [37]:
df = pd.read_csv(
    "output/buildingstock/재고지수.csv",
    dtype={0: "object", "시군구명": "object"},
    # index_col=0
    # na_values=["-"],
)
df = df.set_index(df.columns[0])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 250 entries, 11110 to 50130
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   시군구명         250 non-null    object
 1   연면적_합계       250 non-null    int64
 2   주거용          250 non-null    int64
 3   상업용          250 non-null    int64
 4   공업용          250 non-null    int64
 5   교육및사회용       250 non-null    int64
 6   기타           250 non-null    int64
 7   주민등록인구       250 non-null    int64
 8   재고지표_주거용     250 non-null    float64
 9   재고지표_상업용     250 non-null    float64
 10  재고지표_공업용     250 non-null    float64
 11  재고지표_교육및사회용  250 non-null    float64
 12  재고지수_주거용     250 non-null    float64
 13  재고지수_상업용     250 non-null    float64
 14  재고지수_공업용     250 non-null    float64
 15  재고지수_교육및사회용  250 non-null    float64
dtypes: float64(8), int64(7), object(1)
memory usage: 33.2+ KB

In [36]:
df.index

Index(['11110', '11140', '11170', '11200', '11215', '11230', '11260', '11290',
       '11305', '11320',
       ...
       '48740', '48820', '48840', '48850', '48860', '48870', '48880', '48890',
       '50110', '50130'],
      dtype='object', name='Unnamed: 0', length=250)

In [41]:
# Get the numeric columns
numeric_columns = df.select_dtypes(include=["float64"]).columns

# Use pandas display options to format float values without altering the original data
with pd.option_context("display.float_format", "{:.1f}".format):
    # Sort and display top 10 and bottom 10 for each numeric column
    for col in numeric_columns:
        print(f"Top 10 sorted by {col}:")
        display(df[["시군구명", col]].sort_values(by=col, ascending=False).head(10))

        print(f"Bottom 10 sorted by {col}:")
        display(df[["시군구명", col]].sort_values(by=col, ascending=True).head(10))

Top 10 sorted by 재고지표_주거용:

                   시군구명  재고지표_주거용
Unnamed: 0
42760         강원도 평창군             56.8
47900       경상북도 예천군             49.7
48840       경상남도 남해군             48.4
42830         강원도 양양군             47.7
46780       전라남도 보성군             47.6
43760       충청북도 괴산군             47.3
44270       충청남도 당진시             47.1
43800       충청북도 단양군             47.0
48720       경상남도 의령군             46.5
43720       충청북도 보은군             46.5

Bottom 10 sorted by 재고지표_주거용:

                        시군구명  재고지표_주거용
Unnamed: 0
11620          서울특별시 관악구             25.8
41133       경기도 성남시 중원구             26.0
47940            경상북도 울릉군             26.9
46860            전라남도 함평군             27.2
42790              강원도 화천군             27.3
45750            전라북도 임실군             27.5
45790            전라북도 고창군             27.9
11545          서울특별시 금천구             28.5
11305          서울특별시 강북구             29.0
11215          서울특별시 광진구             29.1

Top 10 sorted by 재고지표_상업용:

                     시군구명  재고지표_상업용
Unnamed: 0
11140         서울특별시 중구            124.0
26110         부산광역시 중구             65.4
11110       서울특별시 종로구             59.2
27110         대구광역시 중구             52.8
42760           강원도 평창군             48.4
11680       서울특별시 강남구             46.1
28110         인천광역시 중구             45.8
42770           강원도 정선군             41.4
42820           강원도 고성군             37.7
42210           강원도 속초시             36.3

Bottom 10 sorted by 재고지표_상업용:

                        시군구명  재고지표_상업용
Unnamed: 0
11350          서울특별시 노원구              6.7
11320          서울특별시 도봉구              7.9
11290          서울특별시 성북구              8.4
26320            부산광역시 북구              8.6
41465       경기도 용인시 수지구              8.6
11380          서울특별시 은평구              8.7
11590          서울특별시 동작구              8.7
41111       경기도 수원시 장안구              9.0
41271       경기도 안산시 상록구              9.2
11470          서울특별시 양천구              9.3

Top 10 sorted by 재고지표_공업용:

                        시군구명  재고지표_공업용
Unnamed: 0
43770            충청북도 음성군             79.6
48730            경상남도 함안군             60.6
26440          부산광역시 강서구             55.7
46830            전라남도 영암군             49.3
43750            충청북도 진천군             48.3
47830            경상북도 고령군             48.0
47840            경상북도 성주군             45.4
41650              경기도 포천시             43.6
41273       경기도 안산시 단원구             39.6
46230            전라남도 광양시             37.7

Bottom 10 sorted by 재고지표_공업용:

                       시군구명  재고지표_공업용
Unnamed: 0
11380         서울특별시 은평구              0.0
11620         서울특별시 관악구              0.0
11590         서울특별시 동작구              0.0
11410       서울특별시 서대문구              0.0
11290         서울특별시 성북구              0.0
11650         서울특별시 서초구              0.0
11215         서울특별시 광진구              0.0
27200           대구광역시 남구              0.0
11305         서울특별시 강북구              0.1
11740         서울특별시 강동구              0.1

Top 10 sorted by 재고지표_교육및사회용:

                     시군구명  재고지표_교육및사회용
Unnamed: 0
11110       서울특별시 종로구                   20.0
41820           경기도 가평군                   18.2
30200       대전광역시 유성구                   17.7
42760           강원도 평창군                   16.7
11140         서울특별시 중구                   15.6
45730         전라북도 무주군                   14.4
29110         광주광역시 동구                   14.3
44150         충청남도 공주시                   14.3
42820           강원도 고성군                   13.9
42770           강원도 정선군                   13.4

Bottom 10 sorted by 재고지표_교육및사회용:

                          시군구명  재고지표_교육및사회용
Unnamed: 0
11260            서울특별시 중랑구                    3.1
41450                경기도 하남시                    3.5
41480                경기도 파주시                    3.6
11320            서울특별시 도봉구                    3.6
11380            서울특별시 은평구                    3.7
11305            서울특별시 강북구                    3.8
11545            서울특별시 금천구                    3.8
11470            서울특별시 양천구                    3.9
41570                경기도 김포시                    3.9
48129       경상남도 창원시 진해구                    3.9

Top 10 sorted by 재고지수_주거용:

                   시군구명  재고지수_주거용
Unnamed: 0
42760         강원도 평창군            153.4
47900       경상북도 예천군            134.1
48840       경상남도 남해군            130.6
42830         강원도 양양군            128.8
46780       전라남도 보성군            128.5
43760       충청북도 괴산군            127.6
44270       충청남도 당진시            127.1
43800       충청북도 단양군            126.8
48720       경상남도 의령군            125.6
43720       충청북도 보은군            125.6

Bottom 10 sorted by 재고지수_주거용:

                        시군구명  재고지수_주거용
Unnamed: 0
11620          서울특별시 관악구             69.5
41133       경기도 성남시 중원구             70.1
47940            경상북도 울릉군             72.6
46860            전라남도 함평군             73.3
42790              강원도 화천군             73.7
45750            전라북도 임실군             74.2
45790            전라북도 고창군             75.4
11545          서울특별시 금천구             77.0
11305          서울특별시 강북구             78.4
11215          서울특별시 광진구             78.7

Top 10 sorted by 재고지수_상업용:

                     시군구명  재고지수_상업용
Unnamed: 0
11140         서울특별시 중구            727.9
26110         부산광역시 중구            384.0
11110       서울특별시 종로구            347.4
27110         대구광역시 중구            309.9
42760           강원도 평창군            284.1
11680       서울특별시 강남구            270.6
28110         인천광역시 중구            268.7
42770           강원도 정선군            243.1
42820           강원도 고성군            221.0
42210           강원도 속초시            212.9

Bottom 10 sorted by 재고지수_상업용:

                        시군구명  재고지수_상업용
Unnamed: 0
11350          서울특별시 노원구             39.1
11320          서울특별시 도봉구             46.5
11290          서울특별시 성북구             49.2
26320            부산광역시 북구             50.3
41465       경기도 용인시 수지구             50.5
11380          서울특별시 은평구             50.8
11590          서울특별시 동작구             51.0
41111       경기도 수원시 장안구             52.5
41271       경기도 안산시 상록구             54.0
11470          서울특별시 양천구             54.4

Top 10 sorted by 재고지수_공업용:

                        시군구명  재고지수_공업용
Unnamed: 0
43770            충청북도 음성군            932.2
48730            경상남도 함안군            709.2
26440          부산광역시 강서구            652.5
46830            전라남도 영암군            576.8
43750            충청북도 진천군            565.2
47830            경상북도 고령군            562.5
47840            경상북도 성주군            531.8
41650              경기도 포천시            511.0
41273       경기도 안산시 단원구            463.3
46230            전라남도 광양시            440.9

Bottom 10 sorted by 재고지수_공업용:

                       시군구명  재고지수_공업용
Unnamed: 0
11380         서울특별시 은평구              0.1
11620         서울특별시 관악구              0.2
11590         서울특별시 동작구              0.2
11410       서울특별시 서대문구              0.3
11290         서울특별시 성북구              0.3
11650         서울특별시 서초구              0.3
11215         서울특별시 광진구              0.4
27200           대구광역시 남구              0.5
11305         서울특별시 강북구              0.9
11740         서울특별시 강동구              0.9

Top 10 sorted by 재고지수_교육및사회용:

                     시군구명  재고지수_교육및사회용
Unnamed: 0
11110       서울특별시 종로구                  290.4
41820           경기도 가평군                  264.3
30200       대전광역시 유성구                  257.0
42760           강원도 평창군                  242.4
11140         서울특별시 중구                  226.0
45730         전라북도 무주군                  209.6
29110         광주광역시 동구                  208.2
44150         충청남도 공주시                  207.1
42820           강원도 고성군                  201.4
42770           강원도 정선군                  194.2

Bottom 10 sorted by 재고지수_교육및사회용:

                          시군구명  재고지수_교육및사회용
Unnamed: 0
11260            서울특별시 중랑구                   45.4
41450                경기도 하남시                   51.2
41480                경기도 파주시                   52.7
11320            서울특별시 도봉구                   52.7
11380            서울특별시 은평구                   54.1
11305            서울특별시 강북구                   55.9
11545            서울특별시 금천구                   55.9
11470            서울특별시 양천구                   56.0
41570                경기도 김포시                   56.7
48129       경상남도 창원시 진해구                   56.9